### ISSUE TITLE
Make use of AVX2 assembly instructions

### ISSUE THREAD

**Issue by mewmew** [7i/rand#1]
Hopefully using hexadecimal representation of AVX2 instructions should no longer be needed, as the following commit adds native support for such instruction to the Go assembler.

https://github.com/golang/go/commit/009c002c925e391e5a7a406c9175aefafb6c9e3c

**Comment by 7i** [comment]
Replaced the hex for the VPSLLD and VPADDD instructions as they are now supported :).
Still need VEXTRACTF128, VCVTDQ2PD, VPMULLD and VDIVPD to be free from all the evil hex representations.
On a side-note, after recompiling with all the latest changes from go master branch the benchmarks show a significant increase on my Lenovo x220:
Before:
BenchmarkComplex128-4  	300000000	         6.15 ns/op	2603.45 MB/s
BenchmarkComplex128Go-4	200000000	         6.25 ns/op	2558.90 MB/s
BenchmarkComplexRand-4 	200000000	         7.95 ns/op	2012.56 MB/s

After:
BenchmarkComplex128-4     	300000000	         4.67 ns/op	3427.05 MB/s
BenchmarkComplex128Go-4   300000000	         4.48 ns/op	3569.41 MB/s
BenchmarkComplexRand-4   200000000	         6.61 ns/op	2418.93 MB/s

**Comment by mewmew** [comment]
> Still need VEXTRACTF128, VCVTDQ2PD, VPMULLD and VDIVPD to be free from all the evil hex representations.

It could be fun to submit a pull request upstream adding these instructions to Go :) Anything substantially different about these instructions, or could they be added in the same way as those included with commit https://github.com/golang/go/commit/009c002c925e391e5a7a406c9175aefafb6c9e3c?

**Comment by 7i** [comment]
I think all these will probably be fixed by Russ Cox in the big asm cleanup when Intel x86_64 instructions are parsed out from the Intel instruction pdf's.

https://go-review.googlesource.com/#/c/18840
https://go-review.googlesource.com/#/c/18850
https://github.com/golang/go/issues/14069
